### ISSUE TITLE
Could not run rice Windows 10 

### ISSUE THREAD

**Issue by ThoDuyNguyen** [randy3k/rice#24]
How could I fix the issue

Kind regards

```
C:\Users\tho>echo %R_HOME%
C:\Program Files\R\R-3.4.1

C:\Users\tho>rice
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\rice.exe\__main__.py", line 9, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\rice\__init__.py", line 41, in main
    RiceApplication().run(options)
  File "c:\programdata\miniconda3\lib\site-packages\rice\riceapp.py", line 222, in run
    rsession = RSession()
  File "c:\programdata\miniconda3\lib\site-packages\rice\session.py", line 70, in __init__
    self.libR = PyDLL(str(libR_path))
  File "c:\programdata\miniconda3\lib\ctypes\__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by randy3k** [comment]
That's strange. It means that `rice` is able to locate the library but fails to import it.
Are Windows 10, python and R all in 64-bit?

**Comment by randy3k** [comment]
Could you also try to put the path to `R.exe` to the environment variable `PATH`?

**Comment by ThoDuyNguyen** [comment]
I did add C:\Program Files\R\R-3.4.1\bin to my Path. 

I use Windows 10 Python (miniconda) and R all in 64 bit.

**Comment by randy3k** [comment]
What happens if you do not specific `R_HOME` and just use the `PATH` variable.

By the way, the following works for me.

```cmd
λ set R_HOME=C:\Program Files\R\R-3.4.1

λ rice
R version 3.4.1 (2017-06-30) -- Single Candle
Platform: x86_64-w64-mingw32

r$>
```

**Comment by ThoDuyNguyen** [comment]
```
C:\Users\tho>rice
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\rice.exe\__main__.py", line 9, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\rice\__init__.py", line 41, in main
    RiceApplication().run(options)
  File "c:\programdata\miniconda3\lib\site-packages\rice\riceapp.py", line 222, in run
    rsession = RSession()
  File "c:\programdata\miniconda3\lib\site-packages\rice\session.py", line 70, in __init__
    self.libR = PyDLL(str(libR_path))
  File "c:\programdata\miniconda3\lib\ctypes\__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
The problem is still there.

**Comment by randy3k** [comment]
What happens if you execute the following in python

```
import ctypes
ctypes.PyDLL("C:\\Program Files\\R\\R-3.4.1\\bin\\x64\\R.dll")
```

Does it work or raise the same error?

**Comment by randy3k** [comment]
Does the dll file exist in the directory? I was not able to reproduce it.

**Comment by randy3k** [comment]
How about adding the path to R.exe to the PATH variable?

**Comment by randy3k** [comment]
I figured out why. It is because rice cannot find R dependencies such as `Rblas.dll`.

The latest master should fix it.

**Comment by smllmn** [comment]
I'm running the latest master but having what appears to be the same issue. 

```
>rice
Traceback (most recent call last):
  File "C:\Users\mail\Anaconda3\Scripts\rice-script.py", line 11, in <module>
    load_entry_point('rice==0.0.43.dev1', 'console_scripts', 'rice')()
  File "C:\Users\mail\Anaconda3\lib\site-packages\rice\__init__.py", line 79, in main
    RiceApplication(r_home).run(options)
  File "C:\Users\mail\Anaconda3\lib\site-packages\rice\riceapp.py", line 206, in run
    rsession = RSession(self.r_home)
  File "C:\Users\mail\Anaconda3\lib\site-packages\rice\session.py", line 62, in __init__
    self.libR = PyDLL(str(libR_path))
  File "C:\Users\mail\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

My path variable contains the R directory. I've tried setting the R_HOME variable to no effect. Running
```
import ctypes
ctypes.PyDLL("C:\\Program Files\\R\\R-3.4.3\\bin\\x64\\R.dll") # updated for my R version
```
produces the same error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mail\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by randy3k** [comment]
Thanks for the report. It seems I have made some regression. Could you also make sure the path to `R.dll` is on the `PATH` variable?

**Comment by smllmn** [comment]
Aha, that's done the trick!

**Comment by randy3k** [comment]
0.0.43 is out, there is no need to edit the `PATH` anymore.
