### ISSUE TITLE
RuntimeError: Cannot locate R share library.

### ISSUE THREAD

**Issue by tsai1993** [randy3k/rice#25]
When run `rice` in mac:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/rice", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/rice/__init__.py", line 41, in main
    RiceApplication().run(options)
  File "/Library/Python/2.7/site-packages/rice/riceapp.py", line 268, in run
    rsession = RSession()
  File "/Library/Python/2.7/site-packages/rice/session.py", line 83, in __init__
    raise RuntimeError("Cannot locate R share library.")
RuntimeError: Cannot locate R share library.
```

**Comment by randy3k** [comment]
It seems that you don’t have R installed. What happen if you type just `R` in terminal?

**Comment by tsai1993** [comment]
I reinstalled R and rice worked very well!
Thank you!
