### ISSUE TITLE
traceback

### ISSUE THREAD

**Issue by faridcher** [randy3k/Rice#3]
is `rice` supposed to work in windows environment? I get the following traceback trying to run `rice` from cmd:

```bat
> C:\Users\farid>rice
Traceback (most recent call last):
  File "C:\Python27\Scripts\rice-script.py", line 9, in <module>
    load_entry_point('rice==0.0.9', 'console_scripts', 'rice')()
  File "c:\python27\lib\site-packages\rice\__init__.py", line 19, in main
    RiceApplication().run()
  File "c:\python27\lib\site-packages\rice\application.py", line 247, in run
    mp = create_multi_prompt()
  File "c:\python27\lib\site-packages\rice\application.py", line 224, in create_multi_prompt
    input=vt100 if not is_windows() else None
  File "c:\python27\lib\site-packages\rice\application.py", line 50, in __init__
    super(MultiPrompt, self).__init__(*args, **kwargs)
  File "c:\python27\lib\site-packages\rice\deps\prompt_toolkit\shortcuts\prompt.py", line 256, in __init__
    input = input or get_default_input()
  File "c:\python27\lib\site-packages\rice\deps\prompt_toolkit\input\defaults.py", line 37, in get_default_input
    return create_input()
  File "c:\python27\lib\site-packages\rice\deps\prompt_toolkit\input\defaults.py", line 18, in create_input
    from .win32 import Win32Input
  File "c:\python27\lib\site-packages\rice\deps\prompt_toolkit\input\win32.py", line 227
    yield KeyPress(Keys.BracketedPaste, ''.join(data))
SyntaxError: 'return' with argument inside generator
```
my %r_home% is set to "
```
> C:\Users\farid>echo %r_home%
C:\Program Files\R\R-3.4.1
```

**Comment by randy3k** [comment]
I didn't test python 2.7 on windows but it should work with python 3.5.

**Comment by randy3k** [comment]
I confirm that it doesn't work on python 2.7 on Windows, will fix soon.

**Comment by randy3k** [comment]
I have just filed an [issue](https://github.com/jonathanslenders/python-prompt-toolkit/issues/549) on upstream.

**Comment by randy3k** [comment]
The upstream bug has fixed. Please reinstall the development version of `rice`.
