### ISSUE TITLE
rice does not locate R installation

### ISSUE THREAD

**Issue by pat-s** [randy3k/Rice#6]
Hi there,

I followed the installation instructions and also the FAQs.

My path looks as follows:

`/usr/lib/R/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`

`rice` is installed via pip. However, when starting `rice` I still see:

`-bash: rice: command not found.`

I also tried exporting `R_HOME` and `LD_LIBRARY_PATH`. 

Running Debian 9 (stretch). R 3.4.1 is installed using the backports repo (`/usr/lib/R`).

Any ideas?

Thanks for your work 👍

**Comment by randy3k** [comment]
Where did you install python to? It looks like you are not using ur system python.

**Comment by pat-s** [comment]
Used the normal `apt-get install` method. Its located at `/usr/lib/python[2.7;3;3.5]`

**Comment by randy3k** [comment]
I have also no idea where `rice` was installed. Can you tell from the console log when you are installing it?

**Comment by goldingn** [comment]
I have the same problem on macOS (Sierra 10.12.6), using either python installed via homebrew, or the system python.

#### homebrew
The homebrew python is in my path, and
```
pip install rice
```
puts rice in `/usr/local/lib/python2.7/site-packages/`.
That's in the path for my homebrew python, and I can open a python shell and import rice, so this python can see the installation.

But at a command prompt, I also get:
```
bash: rice: command not found
```
---
#### system
I tried installing rice into the site library for the System python, too, with:
```
PREFIX_PATH="/Users/nick/Library/Python/2.7/lib/python/site-packages/"
pip install --target=$PREFIX_PATH rice
```
again, opening a system python (`/usr/bin/python`) interpreter I can import rice, but at a command prompt I still get:
```
bash: rice: command not found
```

---

I don't understand how OSX is supposed to find rice and know to use python. Maybe there's something obvious I'm missing?

**Comment by randy3k** [comment]
For the homebrew python, it should also install a `rice` script to `/usr/local/bin/rice`.

```
(rmbpro)-~$ which pip
/usr/local/opt/python/libexec/bin/pip
(rmbpro)-~$ pip install -I rice
Collecting rice
Collecting wcwidth (from rice)
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting pygments (from rice)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting six (from rice)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: wcwidth, pygments, six, rice
Successfully installed pygments-2.2.0 rice-0.0.10 six-1.10.0 wcwidth-0.1.7
(rmbpro)-~$ which rice
/usr/local/bin/rice
```

**Comment by goldingn** [comment]
Yeah, it doesn't install that for me:
```
nick:~$ which pip
/usr/local/bin/pip
nick:~$ pip install -I rice
Collecting rice
  Downloading rice-0.0.11.tar.gz (237kB)
    100% |████████████████████████████████| 245kB 1.0MB/s 
Collecting pygments (from rice)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting six (from rice)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting wcwidth (from rice)
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Building wheels for collected packages: rice
  Running setup.py bdist_wheel for rice ... done
  Stored in directory: /Users/nick/Library/Caches/pip/wheels/a3/05/d6/bb4064de3d01db52524e5d42dd8aa7bab2c8f410f3d7994edf
Successfully built rice
Installing collected packages: pygments, six, wcwidth, rice
Successfully installed pygments-2.2.0 rice-0.0.11 six-1.10.0 wcwidth-0.1.7
nick:~$ which rice
nick:~$ rice
bash: rice: command not found
```

**Comment by goldingn** [comment]
```
nick:~$ /usr/local/bin/pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by randy3k** [comment]
it doesn't look like it is the homebrew python, or your Python formula is not up to date. The recent homebrew python doesn't install `pip` to `/usr/local/bin/pip`

Did you modify the `$PATH` variable?
```
(rmbpro)-~$ brew info python
...
<skiped>
...
This formula installs a python2 executable to /usr/local/bin.
If you wish to have this formula's python executable in your PATH then add
the following to ~/.bash_profile:
  export PATH="/usr/local/opt/python/libexec/bin:$PATH"
```

**Comment by goldingn** [comment]
Ah, looks like some permissions were messing up the brew python install, so python was installed but not pip. Now with brew pip, I have:
```
nick:~$ which rice
```
```
/usr/local/bin/rice
```
Yay!
But then:
```
rice
```
```
Traceback (most recent call last):
  File "/usr/local/bin/rice", line 11, in <module>
    sys.exit(main())
  File "/Users/nick/Library/Python/2.7/lib/python/site-packages/rice/__init__.py", line 23, in main
    RiceApplication().run()
  File "/Users/nick/Library/Python/2.7/lib/python/site-packages/rice/application.py", line 128, in run
    mp = create_multi_prompt()
  File "/Users/nick/Library/Python/2.7/lib/python/site-packages/rice/application.py", line 103, in create_multi_prompt
    extra_key_bindings=create_keybindings(),
  File "/Users/nick/Library/Python/2.7/lib/python/site-packages/rice/keybinding.py", line 93, in create_keybindings
    @kb.add('}', filter=insert_mode & is_default_buffer)
  File "/Users/nick/Library/Python/2.7/lib/python/site-packages/rice/deps/prompt_toolkit/key_binding/key_bindings.py", line 160, in add
    keys = tuple(_check_and_expand_key(k) for k in keys)
  File "/Users/nick/Library/Python/2.7/lib/python/site-packages/rice/deps/prompt_toolkit/key_binding/key_bindings.py", line 160, in <genexpr>
    keys = tuple(_check_and_expand_key(k) for k in keys)
  File "/Users/nick/Library/Python/2.7/lib/python/site-packages/rice/deps/prompt_toolkit/key_binding/key_bindings.py", line 304, in _check_and_expand_key
    assert isinstance(key, text_type)
AssertionError
``` 

boo :(

**Comment by randy3k** [comment]
Please upgrade it to 0.0.11, pypi may be still caching the previous version.

Alternatively, install directly via github instead pypi.

```
pip install -I git+https://github.com/randy3k/rice@v0.0.11
```

**Comment by goldingn** [comment]
```
pip install -I git+https://github.com/randy3k/rice@v0.0.11
```
```
...
Successfully installed pygments-2.2.0 rice-0.0.11 six-1.10.0 wcwidth-0.1.7
```
```
nick:~$ rice
Traceback (most recent call last):
  File "/usr/local/bin/rice", line 11, in <module>
    load_entry_point('rice==0.0.11', 'console_scripts', 'rice')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/rice/__init__.py", line 6, in <module>
    from .application import RiceApplication
  File "/usr/local/lib/python2.7/site-packages/rice/application.py", line 11, in <module>
    from prompt_toolkit import Prompt
ImportError: cannot import name Prompt
```

**Comment by goldingn** [comment]
```
nick:~$ pip install Prompt
```
```
Collecting Prompt
  Downloading prompt-0.4.0.tar.gz
Building wheels for collected packages: Prompt
  Running setup.py bdist_wheel for Prompt ... done
  Stored in directory: /Users/nick/Library/Caches/pip/wheels/2f/06/cd/bf73ffcf295f5173c86a972d36445de775aecc6e76d521b46e
Successfully built Prompt
Installing collected packages: Prompt
Successfully installed Prompt-0.4.0
```

**Comment by goldingn** [comment]
but this worked!
```
pip install -U rice
```
```
nick:~$ rice
```
```
R version 3.4.1 (2017-06-30) -- Single Candle
Platform: x86_64-apple-darwin16.7.0

r$>  
```

Thanks so much for your help! I look forward to giving it a go

**Comment by randy3k** [comment]
It was strange. I am glad that you fixed it. Enjoy it~

**Comment by pat-s** [comment]
> I have also no idea where rice was installed. Can you tell from the console log when you are installing it?

```bash
pip show rice

Name: rice
Version: 0.0.11
Summary: R CLI built on top of prompt_toolkit
Home-page: https://github.com/randy3k/rice
Author: Randy Lai
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/patrick/.local/lib/python2.7/site-packages
Requires: pygments, six, wcwidth
```

**Comment by randy3k** [comment]
Did you add `$Home/.local/bin` to PATH?

**Comment by pat-s** [comment]
> Did you add $HOME/.local/bin to PATH?

Just did it now and it works! Maybe you can add this specific Debian9 setting to the README point for expanding PATH? Referring to `$HOME/.local/bin`

Thanks again for your help. Closing as issue is solved

**Comment by randy3k** [comment]
It may be your first few time installing a program on your Linux machine. `$HOME/.local/bin` is a standard location of local binary/script files.
